apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mmlj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mmlj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mmlj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mmlj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mmlj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jdwr-tenant/rhtap-demo-app/hacbs-test-project-mmlj@sha256:b52084f9635551554e43350cdb2e9dc5b7c5ebfbada62e3da64e3215a3302672
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
